version: "3.7"
services:
  crawler:
    build:
      context: .
      dockerfile: ./dockerfiles/generic-module-debug.Dockerfile
      args:
        - MODULE_NAME=crawler
        - MODULE_TAG=v0.1.0
        - MODULE_TARGET=x86_64-unknown-linux-musl
    environment:
      - NATS_URI=nats://nats:4222
      - STARTING_URL=https://lemonde.fr
    depends_on:
      - nats

  keeper:
    build:
      context: .
      dockerfile: ./dockerfiles/generic-module-debug.Dockerfile
      args:
        - MODULE_NAME=keeper
        - MODULE_TAG=v0.1.0
        - MODULE_TARGET=x86_64-unknown-linux-musl
    environment:
      - NATS_URI=nats://nats:4222
      - DATABASE_URI=postgresql://postgres:password@database/keeper
    depends_on:
      - nats
      - database

  planner:
    build:
      context: .
      dockerfile: ./dockerfiles/generic-module-debug.Dockerfile
      args:
        - MODULE_NAME=planner
        - MODULE_TAG=v0.1.0
        - MODULE_TARGET=x86_64-unknown-linux-musl
    environment:
      - NATS_URI=nats://nats:4222
      - DATABASE_URI=postgresql://postgres:password@database/keeper
      - STARTING_URL=https://lemonde.fr
    depends_on:
      - nats
      - database

  professor:
    build:
      context: .
      dockerfile: ./dockerfiles/local-module-debug.Dockerfile
    environment:
      - DATABASE_URI=postgresql://postgres:password@database/keeper
    depends_on:
      - database

  nats:
    image: "nats"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    restart: unless-stopped

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keeper
    ports:
      - "5432:5432"
    restart: unless-stopped
